# Generated by Django 3.0.5 on 2020-05-15 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200514_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Technical', 'Technical'), ('Non Technical', 'Non Technical')], max_length=200, null=True),
        ),
    ]
